#!/usr/bin/env python3
import argparse
import json
import os
import sys
import traceback

import numpy as np
import onnxruntime as ort
from PIL import Image

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from src.onnx_configs import get_config_for_model, MODEL_CONFIGS
from src.onnx_preprocess import preprocess_model


def load_session(model_path: str, use_gpu: bool) -> ort.InferenceSession:
    providers = ["CUDAExecutionProvider", "CPUExecutionProvider"] if use_gpu else ["CPUExecutionProvider"]
    return ort.InferenceSession(model_path, providers=providers)


def postprocess_image(output: np.ndarray, channels: int) -> Image.Image:
    out = np.squeeze(output, axis=0)
    if out.ndim == 3 and out.shape[0] >= 3:
        out = out[:3] if channels >= 3 else out
    out = np.transpose(out, (1, 2, 0))
    out = np.clip((out + 1.0) * 127.5, 0, 255).astype(np.uint8)
    return Image.fromarray(out)


def format_io_meta(session: ort.InferenceSession) -> dict:
    return {
        "inputs": [{"name": i.name, "shape": i.shape, "type": i.type} for i in session.get_inputs()],
        "outputs": [{"name": o.name, "shape": o.shape, "type": o.type} for o in session.get_outputs()],
    }


def build_preprocess_doc(config: dict, meta: dict) -> str:
    lines = [
        f"- align: {config['align']}",
        f"- input_size: {config['input_size']}",
        f"- normalize: {config['normalize']}",
    ]
    for name, inp in meta.get("per_input", {}).items():
        det = inp.get("detector", "n/a")
        skipped = inp.get("skipped_align", False)
        lines.append(f"- input `{name}`: {inp['path']} (detector={det}, skipped_align={skipped})")
    return "\n".join(lines)


def run_model(model_path, config, args, results_dir, preprocessed_dir, doc_entries):
    model_name = os.path.basename(model_path).replace(".onnx", "")
    entry = {
        "model": model_path,
        "status": "failed",
        "error": None,
        "output_path": None,
        "preprocess_meta": None,
    }
    try:
        overrides = {}
        if args.image and "22.png" in config["inputs"]:
            overrides["22.png"] = os.path.join(args.imgs_dir, args.image)
        if args.source and "0.png" in config["inputs"]:
            overrides["0.png"] = os.path.join(args.imgs_dir, args.source)

        tensors, meta = preprocess_model(config, args.imgs_dir, preprocessed_dir, model_name, overrides)
        entry["preprocess_meta"] = meta

        session = load_session(model_path, use_gpu=not args.cpu)
        entry["onnx_io"] = format_io_meta(session)

        if config["output_type"] == "classification":
            out_names = config["output_names"]
            outputs = session.run(out_names, tensors)
            result = {}
            for name, arr in zip(out_names, outputs):
                flat = np.squeeze(arr)
                result[name] = {
                    "shape": list(arr.shape),
                    "values": flat.tolist() if flat.size > 1 else float(flat),
                }
                if flat.size > 1:
                    result[name]["argmax"] = int(np.argmax(flat))
            out_path = os.path.join(results_dir, f"{model_name}.json")
            payload = {"model": os.path.basename(model_path), "inputs": meta, "outputs": result, "status": "ok"}
            with open(out_path, "w") as f:
                json.dump(payload, f, indent=2)
        else:
            outputs = session.run(None, tensors)
            img = postprocess_image(outputs[0], config.get("output_channels", 3))
            out_path = os.path.join(results_dir, f"{model_name}.png")
            img.save(out_path)

        entry["status"] = "ok"
        entry["output_path"] = out_path
    except Exception as e:
        entry["error"] = str(e)
        traceback.print_exc()

    doc_entries.append((model_name, config, entry))
    return entry


def write_models_md(results_dir, doc_entries):
    lines = ["# ONNX Models I/O Documentation\n", "Generated by `src/run_all_onnx.py`\n"]
    for model_name, config, entry in doc_entries:
        lines.append(f"## {model_name}\n")
        if os.path.isfile(entry["model"]):
            size_mb = os.path.getsize(entry["model"]) / (1024 * 1024)
            lines.append(f"- **File:** `{entry['model']}` ({size_mb:.2f} MB)\n")
        if entry.get("onnx_io"):
            lines.append("### ONNX I/O\n")
            for inp in entry["onnx_io"]["inputs"]:
                lines.append(f"- Input `{inp['name']}`: shape={inp['shape']}, type={inp['type']}\n")
            for out in entry["onnx_io"]["outputs"]:
                lines.append(f"- Output `{out['name']}`: shape={out['shape']}, type={out['type']}\n")
        lines.append("### Preprocessing\n")
        if entry.get("preprocess_meta"):
            lines.append(build_preprocess_doc(config, entry["preprocess_meta"]) + "\n")
        lines.append("### Run Result\n")
        lines.append(f"- Status: **{entry['status']}**\n")
        if entry.get("output_path"):
            lines.append(f"- Output: `{entry['output_path']}`\n")
        if entry.get("error"):
            lines.append(f"- Error: {entry['error']}\n")
        lines.append("\n")
    md_path = os.path.join(results_dir, "MODELS.md")
    with open(md_path, "w") as f:
        f.writelines(lines)
    print(f"Wrote {md_path}")


def resolve_input_path(filename: str, args) -> str:
    """Map a config-declared input filename ("22.png"/"0.png") to the CLI-overridden path."""
    if filename == "22.png":
        return os.path.join(args.imgs_dir, args.image)
    if filename == "0.png":
        return os.path.join(args.imgs_dir, args.source)
    return os.path.join(args.imgs_dir, filename)


def validate_input_images(args) -> None:
    """Ensure every input image referenced by any model config exists on disk."""
    required_filenames = {fn for cfg in MODEL_CONFIGS.values() for fn in cfg["inputs"]}
    missing = []
    for filename in sorted(required_filenames):
        path = resolve_input_path(filename, args)
        if not os.path.isfile(path):
            missing.append(path)
    if missing:
        sys.exit("Missing required input image(s):\n  " + "\n  ".join(missing))


def main():
    parser = argparse.ArgumentParser(description="Batch ONNX inference for all models")
    parser.add_argument("--models-dir", default=os.path.join(REPO_ROOT, "models"))
    parser.add_argument("--imgs-dir", default=os.path.join(REPO_ROOT, "imgs"))
    parser.add_argument("--results-dir", default=os.path.join(REPO_ROOT, "results"))
    parser.add_argument("--image", default="22.png", help="Override default 22.png")
    parser.add_argument("--source", default="0.png", help="Override face_swap source")
    parser.add_argument("--cpu", action="store_true")
    args = parser.parse_args()

    os.makedirs(args.results_dir, exist_ok=True)
    preprocessed_dir = os.path.join(args.results_dir, "_preprocessed")
    os.makedirs(preprocessed_dir, exist_ok=True)

    validate_input_images(args)

    doc_entries = []
    for fname in sorted(os.listdir(args.models_dir)):
        if not fname.endswith(".onnx"):
            continue
        model_path = os.path.join(args.models_dir, fname)
        config = get_config_for_model(model_path)
        if config is None:
            print(f"WARN: no config for {fname}, skipping")
            continue
        print(f"Running {fname}...")
        run_model(model_path, config, args, args.results_dir, preprocessed_dir, doc_entries)

    write_models_md(args.results_dir, doc_entries)


if __name__ == "__main__":
    main()
